# Comment to be posted to on first time issues
newIssueWelcomeComment: |
 Thanks for opening this issue! ğŸ¤—
 Wishing you a great [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com) ğŸ™Œ ğŸ‰ âš¡ï¸
 **Are you looking for beginner-friendly issues? Check out [this](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/) repo.**
 
 ğŸ“¢ Spread the word about [@SakshamAgrwl/GFG-DSA-Problem-Solution](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/) repo across your social media channels to help get others involved!
 
 [![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/SakshamAgrwl)
 
 **Show some â¤ï¸**
    - Consider leaving a â­ [here](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/).
    - Follow @SakshamAgrwl for more updates.
 
 #### Say Hi on [Linkedin](https://www.linkedin.com/in/saksham-agarwal-1286a09m/)! ğŸ‘‹
 

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
 Thanks for opening this pull request! ğŸ¤—
 Wishing you a great [Hacktoberfest 2020](https://hacktoberfest.digitalocean.com) ğŸ™Œ ğŸ‰ âš¡ï¸
 **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/) repo.**
 
 ğŸ“¢ Spread the word about [@SakshamAgrwl/GFG-DSA-Problem-Solution](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/) repo across your social media channels to help get others involved! 
 
 [![Open Source Love](https://badges.frapsoft.com/os/v2/open-source.svg?v=103)](https://github.com/SakshamAgrwl)
 
 **Check out few other repos below** ğŸš€
 
 **Show some â¤ï¸**
    - Consider leaving a â­ [here](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/).
    - Follow @SakshamAgrwl for more updates.
    
 #### Say Hi on [Linkedin](https://www.linkedin.com/in/saksham-agarwal-1286a09m/)! ğŸ‘‹
  
 PS: Please add @SakshamAgrwl as a reviewer if you haven't added.
 

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
 Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
 
 **Show some â¤ï¸**
    - Consider leaving a â­ [here](https://github.com/SakshamAgrwl/GFG-DSA-Problem-Solutions/).
    - Follow @SakshamAgrwl for more updates.
 
